version: '3.8'

services:
  server:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Add your environment variables here
      # - SUPABASE_URL=${SUPABASE_URL}
      # - SUPABASE_KEY=${SUPABASE_KEY}
      # - SUPABASE_DB_URL=${SUPABASE_DB_URL}
    env_file:
      - .env
    volumes:
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service
  server-dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    profiles:
      - dev
