openapi: 3.1.0
info:
  title: Health API
  version: 1.0.0
  description: API for health checks
servers:
  - url: http://localhost:3000
    description: Local server
tags:
  - name: Health
    description: Health check operations
    externalDocs:
      url: https://github.com/martinrebo/expo-lab
      description: Github repository. Find more info here
paths:
  /api/health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API server
      tags:
        - Health
      security: [] # No authentication required for health check
      responses:
        "200":
          description: Server is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [healthy]
          description: Health status of the server
        timestamp:
          type: string
          format: date-time
          description: Current server timestamp
        uptime:
          type: number
          description: Server uptime in seconds
        version:
          type: string
          description: API version following semantic versioning
        build:
          type: object
          description: Build information
          properties:
            number:
              type: string
              description: Build number from CI/CD pipeline
            date:
              type: string
              format: date-time
              description: Build date and time
            commit:
              type: string
              description: Git commit hash
          required:
            - number
            - date
            - commit
        environment:
          type: string
          enum: [development, staging, production]
          description: Current deployment environment
        server:
          type: object
          description: Server runtime information
          properties:
            nodeVersion:
              type: string
              description: Node.js version
            platform:
              type: string
              description: Operating system platform
            arch:
              type: string
              description: CPU architecture
          required:
            - nodeVersion
            - platform
            - arch
      required:
        - status
        - timestamp
        - uptime
        - version
        - build
        - environment
        - server
      example:
        status: "healthy"
        timestamp: "2025-09-04T12:00:00.000Z"
        uptime: 3600
        version: "1.1.1"
        build:
          number: "42"
          date: "2025-09-04T00:00:00.000Z"
          commit: "abc123f"
        environment: "production"
        server:
          nodeVersion: "v18.20.0"
          platform: "linux"
          arch: "x64"
